(test
 (name test_testcontainers)
 (package testcontainers)
 (modules
  test_testcontainers
  test_port
  test_volume
  test_container_request
  test_wait_strategy
  test_error
  test_docker_client
  test_container
  test_file_copy
  test_network
  test_wait_strategy_integration)
 (libraries testcontainers alcotest alcotest-lwt lwt lwt.unix)
 (preprocess
  (pps lwt_ppx)))
