[book]
authors = ["benodiwal"]
language = "en"
src = "src"
title = "Testcontainers OCaml"
description = "Integration testing with real dependencies in OCaml"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/benodiwal/testcontainers-ocaml"
edit-url-template = "https://github.com/benodiwal/testcontainers-ocaml/edit/main/docs/src/{path}"
site-url = "/testcontainers-ocaml/"
cname = ""
additional-css = []
additional-js = []
no-section-label = false

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-hierarchical-nav = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
